### ISSUE TITLE
nothing happen?

### ISSUE THREAD

**Issue by skydiablo** [LavissaWoW/inventree-ipn-generator#10]
hi, i have installed your plugin, but just nothing happen???

![image](https://github.com/user-attachments/assets/805b9246-fff8-45cd-aba6-e1bdfb936a5e)

![image](https://github.com/user-attachments/assets/6b975eca-6373-48c8-85cd-3299b09706bb)

![image](https://github.com/user-attachments/assets/7d697b19-43b2-4fac-9cb7-2441c28861d9)

if i create a new part or edit one, no auto-fill is happen?

any suggestions?

**Comment by LavissaWoW** [comment]
Hi,

The plugin doesn't auto-fill the part form itself, but will add an IPN to a part after it's been created or edited.
This is due to it relying on the event integration of InvenTree. 

If creating and/or saving parts still isn't adding an IPN, check the following:

1. In the InvenTree admin panel, are there any scheduled tasks in the queue? If your server worker processes gets bogged down, the plugin won't work. Clearing the queue will temporarily fix the problem, but I would advise to work out why tasks won't get performed.
2. If you've recently installed the plugin, attempt to restart the InvenTree service completely
3. Download a newer version of the plugin. The current release is 0.1.2.

**Comment by skydiablo** [comment]
okay, cool thx, i dont know why, bit it seems to run...
